routes/web.php
<?php
use App\Models\Jobseeker;
use App\Models\Employer;
use Illuminate\Support\Facades\Input;
use App\Models\Fabric;
use Illuminate\Http\Request;
use App\Models\CSV;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/abc','JobpositionController@test');
Route::get('manual_discharged','JobseekerController@manualDischarged');

//jobseeker list come from job browse feature from messenger
Route::get('jobseeker-jobbrowse/{type?}','JobseekerController@jobseeker_jobbrowse');
//Jobseeker list which is applied jobs and which has stage and status
Route::get('jobseeker-jobapplied','JobseekerController@jobseeker_jobapplied');
//dependent dropdown for stage and status
Route::get('myform',array('as'=>'myform','uses'=>'StageController@myform'));
Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'StageController@myformAjax'));

//dependent dropdown for stage and status
Route::get('jobtitle/ajax/{id}',array('as'=>'jobtitle.ajax','uses'=>'JobpositionController@jobtitleAjax'));

// test json response
Route::get('/api/jobposition/{id}','WebhookController@showJobposition');
Route::post('apply-job','WebhookController@applyJob');
Route::get('/api/jobposition-req/{id}','WebhookController@showReqJobposition');
Route::get('/json','WebhookController@json_test');
Route::get('generate_cv/{jobseeker}','WebhookController@autoReplyCV');

//urgent section
Route::get('/reminder','JobseekerController@reminder');
//for web scraping
Route::get('/phantomjs','PhantomjsController@index' );
Route::get('/scraper-24jobs','WebScraperController@scrape_24jobs_com_mm');
Route::get('/scraper-jobnet','WebScraperController@scrape_jobnet_com_mm');
Route::get('scrapetest2','WebScraperController@index');
Route::get('/scapetest','WebScraperController@scrapetest')->name('scrapetest.index');


// Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);
Route::get('jobfunction',['uses'=>'Jobs\JobfunctionController@manageCategory']);
Route::post('add-category',['as'=>'add.category','uses'=>'Jobs\JobfunctionController@addCategory']);


// job position and job posts
Route::get('freejob','JobpositionController@freejob');
Route::get('paidjob','JobpositionController@paidjob');
Route::post('seft/jobposition/{position}','JobpositionController@update');
Route::resource('jobposition','JobpositionController');
Route::post ( '{route}/global/search', 'SearchController@search');
// Route::resource('jobsavailable','JobavailableController');
Route::resource('jobsavailable-paid','JApaidController');


//checklist section
Route::resource('checklists','ChecklistController');
Route::get('checklist-count','ChecklistController@count');
Route::get('test','ChecklistController@test');
Route::group(['namespace' => 'Checklist'], function()
    {   
Route::resource('checklists-emp','ChecklistempController');
Route::resource('checklists-js','ChecklistjsController');
Route::get('downloadExcelCLEMP/{type}', 'ChecklistempController@downloadExcel');
Route::get('downloadExcelCLJS/{type}', 'ChecklistjsController@downloadExcel');
    });
Route::get('jobseeker-calls','ChecklistController@jobseeker_calls');

//jobposition section
Route::get('jobmatch-free','JobpositionController@jobmatchfree');
Route::get('jobmatch-paid','JobpositionController@jobmatchpaid');
Route::get('jobpositions/{id}/create','JobpositionController@create')->name('jobpositions.create');
Route::patch('/jobpositions/{id}','JobseekerController@update')->name('jobpositions.update');
// Route::get('jobsavailable/show/{id}','JobavailableController@show')->name("jobsavailable.show")->middleware('auth');

//Email Section
Route::get('/email', 'HomeController@index')->name('home.index');
Route::post('email/sending','HomeController@sendingEmail')->name('sending');
Route::get('sendbasicemail','MailController@basic_email');
Route::get('sendhtmlemail','MailController@html_email');
Route::get('sendattachmentemail','MailController@attachment_email');

//EmployerCalllogController Section
Route::resource('employercalllogs','EmployercalllogController');
Route::post('employercalllogs-create','EmployercalllogController@employercallogstore')->name('employercalllogs-create.store');

//for connection with chatfuel and laravel
Route::resource('webhook','WebhookController');
Route::post('webhook2','WebhookController@webhooktest');

//Jobseeker CalllogController
Route::get('/todo','CalllogController@todo')->name('todo.index');
Route::post('/todo/{todo}','CalllogController@todoupdate')->name('todo.update');
Route::get('calllogs/{stage?}','CalllogController@index')->name("calllogs.index");
//Route::resource('calllogs', 'CalllogController');
Route::get('calllogs/create/0','CalllogController@create')->name('calllogs.create');
Route::post('calllogs','CalllogController@store')->name('calllogs.store');
Route::get('calllogs/{callog}','CalllogController@show')->name('calllogs.show');
Route::get('calllogs/{callog}/edit','CalllogController@edit')->name('calllogs.edit');
Route::post('calllogs/{callog}','CalllogController@update')->name('calllogs.update');
Route::delete('calllogs/{callog}','CalllogController@destroy')->name('calllogs.destroy');
Route::patch('/updateisdone/{calllog}','CalllogController@isdone')->name('calllog.isdone');
Route::get('not_match','CalllogController@notMatch');

//EmployerController Section
// autocomplete test
Route::get('/todo-em','EmployercalllogController@todo_em');
Route::get('autocomplete',array('as'=>'autocomplete','uses'=>'EmployerController@autocomplete'));
Route::get('export', 'EmployerController@exportExcel');
Route::get('autocomplete2',array('as'=>'autocomplete2','uses'=>'EmployerController@index2'));
Route::get('searchajax',array('as'=>'searchajax','uses'=>'EmployerController@autoComplete2'));
Route::resource('employers','EmployerController');
Route::get('employers/{id}/send','EmployerController@send')->name('employers.send');
Route::get('employers/{id}/send2','EmployerController@send2')->name('employers.send2');
Route::get('employers/{id}/send3','EmployerController@send3')->name('employers.send3');
Route::patch('/updatestatusemp/{employer}','EmployerController@updatestatus')->name('employers.updatestatus');


//export excel
Route::get('downloadExcelEMP/{type}', 'EmployerController@downloadExcel');
Route::get('downloadExcelEMPCL/{type}', 'EmployercalllogController@downloadExcel');
Route::get('downloadExcelJS/{type}', 'JobseekerController@downloadExcel');
Route::get('downloadExcelCL/{type}', 'CalllogController@downloadExcel');

//JobseekerController Section

Route::patch('/updatestatusjs/{jobseeker}','JobseekerController@updatestatus')->name('jobseekers.updatestatus');

Route::patch('/updatestatusjs-additionalfield/{jobseeker}','JobseekerController@add_additionalfield')->name('jobseekers.add_additionalfield');

Route::get('jobseekers/show/{id}','JobseekerController@show')->name("jobseekers.jobseeker_detail")->middleware('auth');

Route::get('appointed-jobseeker','JobseekerController@appointed');
Route::get('newjs','JobseekerController@newjs');
Route::get('mypdf','JobseekerController@pdf');
Route::get('mypdf/{id}','JobseekerController@pdf')->name("jobseekers.mypdf");
Route::get('newjobseekers','NewjobseekerController@index');
Route::get('jobseekers','JobseekerController@index')->name("jobseekers.index")->middleware('auth');
Route::get('jobseekers/send_cv/{id}','JobseekerController@sendcv')->name('jobseekers.send_cv');
Route::get('jobseekers/send','JobseekerController@send');
Route::post('jobseekers/send','JobseekerController@send');
Route::get('jobseekerdata','JobseekerController@index2')->name('jobseekers.datatable');
Route::get('jobseekersjson','JobseekerController@getJoinsData')->name('jobseekers.datajoin');
Route::get('jobseekerslist','JobseekerController@getJoins')->name("jobseekers.json");
Route::get('/old-appointment','JobseekerController@old_appointment_js');
Route::get('jquery',['as'=>'jquery','uses'=>'JobseekerController@loadMore']);
Route::get('/duplicates','JobseekerController@duplicates')->name('duplicates.index');
Route::get('/count','JobseekerController@count')->name('counts.index');
Route::get("js/data", 'JobseekerController@data')->name("js.data");
Route::get('jsdata','JobseekerController@jsdata');
Route::resource('jobseekers','JobseekerController');
Route::get('jobseekers/discharge/{id?}','CalllogController@discharged');

Route::get('/', 'HomeController@welcome')->name('home');

//for the keys
Route::resource('certificates','CertificateController');
Route::resource('jobfunctions','JobFunctionController');
Route::resource('jobtitles','JobTitlesController');
Route::resource('townships','TownshipController');
Route::resource('callreasons','CallreasonController');
Route::resource('skill_1','SkillController');
Route::resource('skill_2','Skill2Controller');
Route::resource('jobindustry','IndustryController');
Route::resource('wards','WardController');
Route::resource('status','StatusController');
Route::resource('users','UserController');
Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory']);
Route::get('automatch/{param}','GeneralController@autoMatch');
Route::get('set_status/{id}','GeneralController@setStatus');
Route::get('set_employer/{id}','GeneralController@setEmployer');
Route::get('csv_import',function(){
	return view('csv_import');
});
Route::post('csv_import',function(Request $request){
	$csv = new CSV($request->all());
	$csv->import();
});

app/Models/Employercalllog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employercalllog extends Model
{

    public function employer()
    {
        return $this->belongsTo('App\Models\Employer','employer_id');
    }

    public function Mystatus()
    {
      return $this->belongsTo('App\Models\Employerstatus' , 'status');
    }
    
  	public function author()
  	{
  		return $this->belongsTo('App\User','caller_receiver');
  	}

    public function Myempcallreason()
    {
      return $this->belongsTo('App\Models\Employercallreason' , 'call_reason');
    }

    public function scopeSearch($query, $request)
          { 
        
        if ($request->employer_name!='' || $request->employer_id){
              $query->join('employers','employercalllogs.employer_id','=','employers.id');
          } 
        if ($request->caller_receiver!=''){
              $query->join('users','employercalllogs.caller_receiver','=','users.id');
          }    
        if ($request->status!=''){
              $query->join('employerstatuses','employercalllogs.status','=','employerstatuses.id');
          }     
        if ($request->call_reason!=''){
              $query->join('employercallreasons','employercalllogs.call_reason','=','employercallreasons.id');
          } 
        if ($request->employer_id!='') {       
            $query->where('employers.id',$request->employer_id);
        }    
        if ($request->remark!='') {       
          $query->where('employercalllogs.remark', 'LIKE', '%' .$request->remark. '%' );
        }    
        if ($request->type_of_call!='') {       
          $query->where('type_of_call', 'LIKE', '%' . $request->type_of_call . '%' );
        }
        if ($request->call_reason!='') {       
          $query->where('employercallreasons.description', 'LIKE', '%' . $request->call_reason . '%' );
        }    
        if ($request->status!='') {       
          $query->where('employerstatuses.description', 'LIKE', '%' . $request->status . '%' );
        }
        if ($request->call_back_date!='') {       
          $query->where('call_back_date',$request->call_back_date);
        }
        if ($request->created_at!='') {       
          $query->where('created_at', '=',$request->created_at.' 00:00:00');
        }
        if ($request->caller_receiver!='') {
         $query->where('users.name',$request->caller_receiver);
        }
        if ($request->employer_name!='') {
         $query->where('employer_name', 'LIKE', '%' . $request->employer_name . '%' );
        }          
       
        return $query->select('employercalllogs.*');     
      }



}

resources/views/backend/employer_calllogs/index.blade.php
@extends('layouts.dashboard')


@section('section')
<br><br>

<div class="row">
  <div class="col-md-12">
    <center><h2 class="" style="display: inline-block;">Employer Call Log List</h2></center>

  </div>

<div class="row">


    <div class="col-sm-12 search-fix">

   
        <div class="col-md-12 alert alert-success alert-block">
         @isset($js_id)
          ID : <b>{{$js_id}} </b>
         @endisset

         @isset($fullname)
          Full Name : <b>{{$fullname}} </b>
         @endisset

         @isset($call_reason)
          Call Reason : <b>{{$call_reason}} </b>
         @endisset
          
         @isset($remark_calllog)
           Remark : <b>{{$remark_calllog}} </b>
         @endisset

         @isset($type_of_call)
          Type of Call : <b>{{$type_of_call}} </b>
         @endisset

         @isset($caller_receiver)
          Caller Receiver : <b>{{$caller_receiver}} </b>
         @endisset

         @isset($call_back_date)
          Call Back Date : <b>{{$call_back_date}} </b>
         @endisset
         
         @isset($created_at)
          Created Date : <b>{{$created_at}} </b>
         @endisset

 </div>
</div>

<div class="container-fluid">
<a href="{{ route('employercalllogs.create') }}" class="btn btn-primary pull-right">Create Employer Call Log</a>
    
    <a href="{{ URL::to('downloadExcelEMPCL/xls') }}"><button class="btn btn-success pull-right">Excel xls</button></a>
    <a href="{{ URL::to('downloadExcelEMPCL/csv') }}"><button class="btn btn-success pull-right"> CSV</button></a>
    <button class="btn btn-default for-hide-search-form">Show Search Form</button>
</div>
<br>

  <div class="row">

          <div class="col-md-12">

                <div class="box box-body">
                     {!! Form::open(['url'=>'/employercalllogs','method'=>'GET', 'class'=>'form', 'id'=>'search_data']) !!}
      
                       <div class="form-group col-md-6">        
                          <input type="text" name="employer_id" placeholder="ID" value="{{ request()->input('employer_id')}}" class="form-control"/>
                       </div>

                        <div class="form-group col-md-6">
                          <input type="text" name="employer_name" placeholder="Employer Name" value="{{ request()->input('employer_name')}}" class="form-control"/>
                        </div>
                       
                        <div class="form-group col-md-6">                     
                              <?php $call_reason = \App\Models\Employercallreason::all(); ?>
                            <select id="val_select" name="call_reason" class="form-control select2">
                                <option value="{{ request()->input('call_reason')}}">
                                <?php $label =request()->input('call_reason');
                                if(isset($label))
                                  echo $label;
                                else
                                  echo "Choose Call Reason";
                               ?></option>
                                @foreach($call_reason as $row)
                                      <option value="{{ $row->description }}" @if(old('call_reason') == $row->description) selected @endif> {{ $row->description }} </option>
                                @endforeach
                            </select>
                        </div>                       

                        <div class="form-group col-md-6">
                            <?php $status = \App\Models\Employerstatus::all(); ?>
                            <select id="val_select" name="status" class="form-control select2">
                                <option value="{{ request()->input('status')}}">
                                <?php $label =request()->input('status');
                                if(isset($label))
                                  echo $label;
                                else
                                  echo "Choose Status";
                               ?></option>
                                @foreach($status as $row)
                                      <option value="{{ $row->description }}" @if(old('call_reason') == $row->description) selected @endif> {{ $row->description }} </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group col-md-6">    
                            <input type="text" name="remark" placeholder="Remark" value="{{ request()->input('remark')}}" class="form-control"/>
                        </div>

                        <div class="form-group col-md-6">
                            <select class="form-control select2" name="type_of_call">
                              <option value="{{ request()->input('type_of_call')}}">
                              <?php $label =request()->input('type_of_call');
                                if(isset($label))
                                  echo $label;
                                else
                                  echo "Type of Call";

                               ?></option>
                              <option value="Incoming Call">Incoming Call</option>
                              <option value="Outgoing Call">Outgoing Call</option>                              
                           </select>
                        </div>

                       <div class="form-group col-md-6">
                            <?php $authors = \App\User::all(); ?>
                            <select id="val_select" name="caller_receiver" class="form-control select2">
                                <option value="{{ request()->input('caller_receiver')}}">
                                <?php $label =request()->input('caller_receiver');
                                  if(isset($label))
                                    echo $label;
                                  else
                                    echo "Caller Receiver";
                                 ?></option>
                                @foreach($authors as $row)
                                      <option value="{{ $row->name }}" @if(old('caller_receiver') == $row->name) selected @endif> {{ $row->name }} </option>
                                @endforeach      
                            </select>
                        </div>                       
                        <div class="form-group col-md-4">
                            <a href="{{url('employercalllogs')}}" class="btn btn-flat btn-danger">Reset</a>
                            <button class="btn btn-flat btn-primary">Search</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>

<div class="container-fluid">
    <table>
      <thead>
          <tr style="background-color: #99ccff">
            <th>Action</th>
            <th >ID</th>
            <th>Type of Call</th>
            <th class="employer-name">Name</th>
            <th class="call-back-date">Call Back Date</th>
            <th class="status">Status</th>
            <th class="start-time">Start Time</th>
            <th>Receiver</th>
            <th>Ph Number</th>
            <th>Industrial Zone</th>
            <th>Call Reason</th>            
            <th>Meeting</th>      
            <th>Remark</th>
            <th>Email Sent?</th>
            <th>Caller/Receiver</th>
      </thead>
      <tbody>

        @foreach($employers as $employer )
       <tr class="" style="background-color:#cce6ff;">
           <td><a href="{{ route('employers.show', $employer->employer_id) }}" class="btn btn-info btn-xs" target="_blank"><i class="glyphicon glyphicon-eye-open"></i> </a></td>
            <td>{{$employer->employer_id}}</td>
            <td>{{ $employer->type_of_call }}</td>
            <td><a href="{{ route('employers.show', $employer->employer_id) }}" target="_blank">{{ $employer->employer['employer_name'] }}</a></td>
            <td>@if(!empty($employer->call_back_date)){{Carbon\Carbon::parse($employer->call_back_date)->format('j-M-y')}} @endif</td>
            <td>{{ $employer->Mystatus['description'] }}</td>
            <td>{{ $employer->created_at }}</td>
            <td>{{ $employer->receiver }}</td>
            <td>{{ $employer->ph_number }}</td>
            <td>{{ $employer->industry_zone }}</td>
            <td>{{ $employer->Myempcallreason['description'] }}</td>
            <td>{{ $employer->meeting }}</td>
            <td>{{ $employer->remark }}</td>
            <td>{{ $employer->email_sent }}</td>
            <td>{{ $employer->author['name'] }}</td>
        </tr>
         @endforeach
      </tbody>
    </table> 

    </div>
    </div>
     <nav>
       <ul class="pagination">
       <li><?php  echo $employers->render(); ?></li>
       </ul>
     </nav>

  
  </div>
</div>
</div>
<style type="text/css">
  
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 3000px;

}
td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
th.call-back-date{
  width: 100px;
}
th.status{
  width: 550px;
}
th.employer-name{
  width: 250px;
}
th.start-time{
  width: 150px;
}
</style>
@stop

resources/views/backend/employer_calllogs/todo_em.blade.php
@extends('layouts.dashboard')


@section('section')
<br><br><br>

<div class="row">
  <div class="col-md-12">
    <center><h2 class="" style="display: inline-block;">Employer Todo List</h2></center>

  </div>
</div>
 
<div class="row">




    <div class="col-sm-12 search-fix">

   
        <div class="col-md-12 alert alert-success alert-block">
     You search for
          @isset($js_id)
          ID : <b>{{$js_id}} </b>
          @endisset

          @isset($fullname)
          Full Name : <b>{{$fullname}} </b>
          @endisset
          
          @isset($call_reason)
          Call Reason : <b>{{$call_reason}} </b>
          @endisset
  
          @isset($remark_calllog)    
          Remark : <b>{{$remark_calllog}} </b>
          @endisset

          @isset($type_of_call)
          Type of Call : <b>{{$type_of_call}} </b>
          @endisset

          @isset($caller_receiver)
          Caller Receiver : <b>{{$caller_receiver}} </b>
          @endisset

          @isset($call_back_date)
          Call Back Date : <b>{{$call_back_date}} </b> 
          @endisset
   
          @isset($created_at)
          Created Date : <b>{{$created_at}} </b>
          @endisset

 </div>
</div>
<div class="row">


  <div class="container-fluid">
    <a href="{{ route('employercalllogs.create') }}" class="btn btn-primary pull-right">Create Employer Call Log</a>
       <!--  <input type="button" value="Refresh Page" onClick="window.location.reload()" class="btn btn-flat btn-primary pull-right"> -->
    <a href="{{ URL::to('downloadExcelEMPCL/xls') }}"><button class="btn btn-success pull-right">Excel xls</button></a>
    <a href="{{ URL::to('downloadExcelEMPCL/csv') }}"><button class="btn btn-success pull-right"> CSV</button></a>
    
    <button class="btn btn-default for-hide-search-form">Show Search Form</button>
  </div>
    <br>

<div class="row">

            <div class="col-md-12">

                <div class="box box-body">
                    {!! Form::open(['url'=>'/todo-em','method'=>'GET', 'class'=>'form', 'id'=>'search_data']) !!}
      
                        <div class="form-group col-md-6">    
                            <input type="text" name="employer_id" placeholder="Employer Id" value="{{ request()->input('employer_id')}}" class="form-control"/>
                        </div>

                        <div class="form-group col-md-6">
                            <input type="text" name="employer_name" placeholder="Employer Name" value="{{ request()->input('employer_name')}}" class="form-control"/>
                        </div>
                    
                        <div class="form-group col-md-6">
                            <?php $call_reason = \App\Models\Employercallreason::all(); ?>
                            <select id="val_select" name="call_reason" class="form-control select2">
                                <option value="{{ request()->input('call_reason')}}">
                                <?php $label =request()->input('call_reason');
                                if(isset($label))
                                  echo $label;
                                else
                                  echo "Choose Call Reason";
                               ?></option>
                                @foreach($call_reason as $row)
                                      <option value="{{ $row->description }}" @if(old('call_reason') == $row->description) selected @endif> {{ $row->description }} </option>
                                @endforeach
                            </select>
                        </div>                       

                         <div class="form-group col-md-6">
                            <?php $status = \App\Models\Employerstatus::all(); ?>
                            <select id="val_select" name="status" class="form-control select2">
                                <option value="{{ request()->input('status')}}">
                                <?php $label =request()->input('status');
                                if(isset($label))
                                  echo $label;
                                else
                                  echo "Choose Status";
                               ?></option>
                                @foreach($status as $row)
                                      <option value="{{ $row->description }}" @if(old('call_reason') == $row->description) selected @endif> {{ $row->description }} </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group col-md-6">    
                            <input type="text" name="remark" placeholder="Remark" value="{{ request()->input('remark')}}" class="form-control"/>
                        </div>

                        <div class="form-group col-md-6">
                          <select class="form-control select2" name="type_of_call">
                            <option value="{{ request()->input('type_of_call')}}">
                            <?php $label =request()->input('type_of_call');
                              if(isset($label))
                                echo $label;
                              else
                                echo "Type of Call";

                             ?></option>
                            <option value="Incoming Call">Incoming Call</option>
                            <option value="Outgoing Call">Outgoing Call</option>                              
                          </select>
                        </div>

                       <div class="form-group col-md-6">
                            <?php $authors = \App\User::all(); ?>
                            <select id="val_select" name="caller_receiver" class="form-control select2">
                                <option value="{{ request()->input('caller_receiver')}}">
                                <?php $label =request()->input('caller_receiver');
                                  if(isset($label))
                                    echo $label;
                                  else
                                    echo "Caller Receiver";

                                 ?></option>
                                @foreach($authors as $row)
                                      <option value="{{ $row->name }}" @if(old('caller_receiver') == $row->name) selected @endif> {{ $row->name }} </option>
                                @endforeach
                            </select>
                        </div>
                     
                        <div class="form-group col-md-4">
                            <a href="{{url('todo-em')}}" class="btn btn-flat btn-danger">Reset</a>
                            <button class="btn btn-flat btn-primary">Search</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>

    <table class="table table-bordered">
      <thead>
          <tr style="background-color: #99ccff">
              <th>Action</th>
              <th>Call log ID</th>
              <th>Employer ID</th>
              <th>Type of Call</th>
              <th>Name</th>
              <th>Call Back Date</th>
              <th>Status</th>
              <th>Start Time</th>
              <th>Receiver</th>
              <th>Ph Number</th>
              <th>Industrial Zone</th>
              <th>Call Reason</th>                     
              <th>Meeting</th>      
              <th>Remark</th>
              <th>Email Sent?</th>
              <th>Caller / Receiver</th>

      </thead>
      <tbody>

        @foreach($employers as $employer )
       
         @if($employer->call_back_date!=null)
         <tr class="" style="background-color:#cce6ff;">
             <td><a href="{{ route('employers.show', $employer->employer_id) }}" class="btn btn-info btn-xs" target="_blank"><i class="glyphicon glyphicon-eye-open"></i> </a></td>
             <td>{{$employer->id}}</td>
             <td>{{$employer->employer['id']}}</td>
              <td>{{ $employer->type_of_call }}</td>
              <td><a href="{{ route('employers.show', $employer->employer_id) }}" target="_blank">{{ $employer->employer['employer_name'] }}</a></td>
              <td>{{Carbon\Carbon::parse($employer->call_back_date)->format('j-M-y')}}</td>
              <td>{{ $employer->Mystatus['description'] }}</td>
              <td>{{ $employer->created_at }}</td>
              <td>{{ $employer->receiver }}</td>
              <td>{{ $employer->ph_number }}</td>
              <td>{{ $employer->industry_zone }}</td>
              <td>{{ $employer->Myempcallreason['description'] }}</td>
              <td>{{ $employer->meeting }}</td>
              <td>{{ $employer->remark }}</td>
              <td>{{ $employer->email_sent }}</td>
              <td>{{ $employer->author['name'] }}</td> 

        </tr>
          @endif
         @endforeach
     
      </tbody>
    </table> 

    </div>
    </div>
         <nav>
       <ul class="pagination">
       <li><?php //  echo $jobseekers->render(); ?></li>
       </ul>
     </nav>

  
  </div>
</div>
</div>
@stop